### ISSUE TITLE
is it still active?

### ISSUE THREAD

**Issue by yunfan** [niclash/forthright#5]
i saw your forthright from forthhub
just ask if it was still in development?

**Comment by niclash** [comment]
This was primarily an exercise in getting experience with the 8266 assembler as well as getting back my ancient passion of Forth. The work on 8266 ceased to progress for reason of TCP/IP not being stable enough for my needs (seems that there are problems when too many packets are sent). And once I stopped my project with 8266, this project kind of died with it.

Primary "insult" is that I couldn't manage to put the whole standard dictionary in Flash memory, and it occupies "too much" of RAM for my liking. I also never got to fully implement the I/O system, which was what I was really keen on, to test my hardware designs interactively.

\ Arduino style names
OUTPUT 6 pinmode  \ set output for GPIO6
INPUT 5 pinmode  \ set input for GPIO5

5 digitalread  \ read GPIO5
1 6 digitalwrite \ set GPIO6

IF/WHEN I get back to ESP8266 or ESP32, I might get back to this, but probably not this year, as I am working on something completely unrelated, but if successful, I will have plenty of time to do these exciting (but non-profitable) projects.

That said, feel free to work on it. My work is Apache License, and the JonesForth that I started from is under Public Domain.

**Comment by yunfan** [comment]
i am not familiar with xtensa's archtecture, are there any quick course on it?
also since my lack of knowledges, is it possible to implement the 3 INS FORTH on xtensa arch? as i knew, that was hard to implement on havard arch, but once you implement it, i think flash size is not the limitation for you

**Comment by niclash** [comment]
I don't know what "3 INS FORTH" is, nor does Google.

**Comment by yunfan** [comment]
check this   
http://pages.cs.wisc.edu/~bolo/shipyard/3ins4th.html
basiclly i think its just a tiny loader&exectutor on the mcu side, and then let the pc side forth to do all the other work

**Comment by niclash** [comment]
I wouldn't call that FORTH, and I have done very similar things in the past, especially in the days of 8031/8032 products we developed early/mid 1980s.

The "problem" with Harvard architectures and the above approach is that you can't feed a program into memory and then execute it, as the program memory is typically not easily modifiable (not like RAM) and RAM can't be used for executing code. For instance, the 8031 had RAM and EPROM completely separate and therefor 64kB of each directly addressable. It was possible to map CODE and DATA into the same address space at the hardware level, effectively going from Harvard to Neumann arch.

No, what I really wanted was an on-target environment, where my own code resided in RAM, easily modifiable over the TTY/WiFi. I pretty much achieved that, including uploading Forth over TTY (Wifi? can't remember) since a Forth program is nothing more than something typed on the TTY, by me or a file loaded via the terminal program.

So, from a Forth perspective, I got what I was looking for, but the TCP/IP proved problematic. Arduino's webserver, another LWIP webserver and one that I wrote from scratch, ALL crashed when serving large content, such as images. The larger the data, the higher probability of crash. Since all 3 showed very similar behavior, I concluded that it was a problem inside the firmware, which I wasn't clever enough to fix. Since then, I have seen one note that it is most likely due to some software watchdog timing out, as not enough time was given for internal maintenance in the firmware, or something to that effect. In the ESP32, that might have been fixed, since it has 2 cores, where one is dedicated for the TCP/IP stack and other firmware functionality, and the second core is for applications. I just haven't had enough time to verify whether that is correct or not, albeit the ESP32 laying on my desk in front of me.

**Comment by yunfan** [comment]
got it, but the esp32 boards sells expensive as an mcu in china, in that price, i would prefer a router chip with huge ram . i used to have a wifi sdcard reader, which only take me $10, and it has small size, with huge ram
check https://wiki.hackerspace.pl/projects:zsun-wifi-card-reader

**Comment by niclash** [comment]
I think I paid $9.50 for the ESP32 dev kit board. I think I have seen as low as $6.50 or so. The modules itself is about a dollar higher than the 8266 modules (I used ESP-12F for about $2). To me, the devkit price is so low that it doesn't matter, and only comes down to whether the product is viable with an additional dollar or so in cost. Sometimes it is not, often it is.
